### ISSUE TITLE
java.lang.NoClassDefFoundError: org/slf4j/Logger

### ISSUE THREAD

**Issue by dh-Chen** [sbordet/oort-chat-demo#1]
when  I run mvn jetty:run -PB, there is a error: "java.lang.NoClassDefFoundError: org/slf4j/Logger" and build fail.
I try to rm $HOME/.m2/repository/\* and the error still exisit.
can you tell me how to solve it.
Thanks~

**Comment by sbordet** [comment]
I don't have this problem, it works fine for me.

You can run `mvn jetty:run -PA` fine, but not `mvn jetty:run -PB` ?

**Comment by dh-Chen** [comment]
`mvn jetty:run -PA` does not work for me either.
The following is the error message, can you have a look at it. 
"[ERROR] Failed to execute goal org.eclipse.jetty:jetty-maven-plugin:9.2.14.v20151106:run (default-cli) on project oort-object-chat-demo: Execution default-cli of goal org.eclipse.jetty:jetty-maven-plugin:9.2.14.v20151106:run failed: A required class was missing while executing org.eclipse.jetty:jetty-maven-plugin:9.2.14.v20151106:run: org/slf4j/Logger"

p.s.
the version of maven I used is 3.05 and jdk1.8
does not it matter?

**Comment by sbordet** [comment]
The Maven version is really old, I suggest you upgrade to the latest, which is 3.3.9.

**Comment by dh-Chen** [comment]
It works!!
Thanks!!
